### ISSUE TITLE
Include Selene configuration

### ISSUE THREAD

**Issue by Sleitnick** [Sleitnick/AeroGameFramework-VSCE#11]
Installations of AGF should include a `selene.toml`.

**Comment by Sleitnick** [comment]
The configuration should probably look something like this:

```toml
std = "roblox"

[rules]
parenthese_conditions = "allow"
multiple_statements = "allow"
global_usage = "allow"

[config]
unused_variable = {allow_unused_self = true}
```
